import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import { User } from '../models/userModel';
import { Client } from '../models/clientModel';
import { Lead } from '../models/leadModel';
import { Meeting } from '../models/meetingModel';
import { Project } from '../models/projectModel';
import { Milestone } from '../models/milestoneModel';
import { Task } from '../models/taskModel';
import { DocumentModel } from '../models/documentModel';
import { NotificationModel } from '../models/notificationModel';
import { ActivityLogModel } from '../models/activityLogModel';
import { InvitationModel } from '../models/invitationModel';

export const seedMasterDatabase = async (quiet: boolean = false): Promise<void> => {
  const log = (...args: any[]) => {
    if (!quiet) console.log(...args);
  };

  log('[DevFlow Master Seed] Connecting to MongoDB database...');
  const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/devflow';

  if (mongoose.connection.readyState !== 1) {
    try {
      await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 4000 });
      log(`[DevFlow Master Seed] Connected to MongoDB at ${mongoose.connection.host}`);
    } catch (err) {
      log(`[DevFlow Master Seed] Local MongoDB unavailable (${(err as Error).message}). Using In-Memory MongoDB...`);
      const { MongoMemoryServer } = await import('mongodb-memory-server');
      const mongoServer = await MongoMemoryServer.create();
      const memoryUri = mongoServer.getUri();
      await mongoose.connect(memoryUri);
      log(`[DevFlow Master Seed] In-Memory MongoDB Connected at ${memoryUri}`);
    }
  }

  log('[DevFlow Master Seed] Wiping ALL existing database collections to eliminate legacy test data...');

  await Promise.all([
    User.deleteMany({}),
    Client.deleteMany({}),
    Lead.deleteMany({}),
    Meeting.deleteMany({}),
    Project.deleteMany({}),
    Milestone.deleteMany({}),
    Task.deleteMany({}),
    DocumentModel.deleteMany({}),
    NotificationModel.deleteMany({}),
    ActivityLogModel.deleteMany({}),
    InvitationModel.deleteMany({}),
  ]);

  log('[DevFlow Master Seed] Collections wiped. Seeding canonical presentation dataset...');

  const demoPassword = 'DevFlow@2026';

  // 1. Seed 12 Team Members
  const usersData = [
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000001'),
      name: 'Alex Morgan',
      email: 'alex.morgan@devflow.demo',
      password: demoPassword,
      role: 'Super Admin',
      department: 'Engineering Leadership',
      skills: ['Node.js', 'TypeScript', 'System Architecture', 'MongoDB', 'Security'],
      workloadPercent: 65,
      availability: 'Available',
      performanceRating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000002'),
      name: 'Olivia Bennett',
      email: 'olivia.bennett@devflow.demo',
      password: demoPassword,
      role: 'Admin',
      department: 'Operations',
      skills: ['Resource Planning', 'Team Operations', 'Operations', 'Compliance'],
      workloadPercent: 45,
      availability: 'Available',
      performanceRating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000003'),
      name: 'Sarah Chen',
      email: 'sarah.chen@devflow.demo',
      password: demoPassword,
      role: 'Project Manager',
      department: 'Product Management',
      skills: ['Agile', 'PM', 'Roadmap Planning', 'Client Communication'],
      workloadPercent: 75,
      availability: 'Available',
      performanceRating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000004'),
      name: 'Rachel Wong',
      email: 'rachel.wong@devflow.demo',
      password: demoPassword,
      role: 'Project Manager',
      department: 'Product Management',
      skills: ['Scrum', 'Project Management', 'Stakeholder Management', 'Jira'],
      workloadPercent: 62,
      availability: 'Available',
      performanceRating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000005'),
      name: 'Daniel Thomas',
      email: 'daniel.thomas@devflow.demo',
      password: demoPassword,
      role: 'Project Coordinator',
      department: 'Operations',
      skills: ['Coordination', 'Scheduling', 'Resource Tracking', 'Reporting'],
      workloadPercent: 40,
      availability: 'Available',
      performanceRating: 4.7,
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000006'),
      name: 'Marcus Vance',
      email: 'marcus.vance@devflow.demo',
      password: demoPassword,
      role: 'Team Lead',
      department: 'Engineering',
      skills: ['React', 'Next.js', 'Node.js', 'System Architecture', 'Microservices'],
      workloadPercent: 88,
      availability: 'Busy',
      performanceRating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000007'),
      name: 'Nina Thomas',
      email: 'nina.thomas@devflow.demo',
      password: demoPassword,
      role: 'Team Lead',
      department: 'Engineering',
      skills: ['Python', 'Cloud Infrastructure', 'Docker', 'Backend APIs', 'PostgreSQL'],
      workloadPercent: 72,
      availability: 'Available',
      performanceRating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000008'),
      name: 'Elena Rostova',
      email: 'elena.rostova@devflow.demo',
      password: demoPassword,
      role: 'Developer',
      department: 'Engineering',
      skills: ['Node.js', 'TypeScript', 'MongoDB', 'Redis', 'Backend APIs'],
      workloadPercent: 70,
      availability: 'Available',
      performanceRating: 4.7,
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000009'),
      name: 'Arjun Nair',
      email: 'arjun.nair@devflow.demo',
      password: demoPassword,
      role: 'Developer',
      department: 'Engineering',
      skills: ['React', 'Next.js', 'TypeScript', 'Frontend', 'REST APIs'],
      workloadPercent: 35,
      availability: 'Available',
      performanceRating: 4.6,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000010'),
      name: 'Kevin Joseph',
      email: 'kevin.joseph@devflow.demo',
      password: demoPassword,
      role: 'Developer',
      department: 'Engineering',
      skills: ['Node.js', 'Express', 'MongoDB', 'Testing', 'GraphQL'],
      workloadPercent: 58,
      availability: 'Available',
      performanceRating: 4.6,
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000011'),
      name: 'David Kim',
      email: 'david.kim@devflow.demo',
      password: demoPassword,
      role: 'Designer',
      department: 'UI/UX',
      skills: ['Figma', 'UI/UX', 'Design Systems', 'Prototyping', 'Tailwind CSS'],
      workloadPercent: 55,
      availability: 'Available',
      performanceRating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000012'),
      name: 'Priya Patel',
      email: 'priya.patel@devflow.demo',
      password: demoPassword,
      role: 'QA',
      department: 'Quality Assurance',
      skills: ['QA Automation', 'API Testing', 'E2E Testing', 'Cypress', 'Playwright'],
      workloadPercent: 80,
      availability: 'Available',
      performanceRating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      status: 'active',
    },
  ];

  const users: any[] = [];
  for (const u of usersData) {
    const created = await User.create(u);
    users.push(created);
  }

  log(`[DevFlow Master Seed] Seeded ${users.length} Users`);

  // 2. Seed 6 Clients
  const clients = await Client.create([
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000101'),
      name: 'Apex Capital Corp',
      company: 'Apex Capital Corp',
      email: 'robert.sterling@apexcapital.com',
      phone: '+1 (555) 234-5678',
      activeProjects: 1,
      totalValue: 18000000,
      status: 'Active',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000102'),
      name: 'Vanguard Health Systems',
      company: 'Vanguard Health Systems',
      email: 'athorne@vanguardhealth.org',
      phone: '+1 (555) 345-6789',
      activeProjects: 1,
      totalValue: 12000000,
      status: 'Active',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000103'),
      name: 'BioHealth Innovations',
      company: 'BioHealth Innovations',
      email: 'e.vance@biohealth.io',
      phone: '+1 (555) 456-7890',
      activeProjects: 1,
      totalValue: 8500000,
      status: 'Active',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000104'),
      name: 'CloudScale Dynamics',
      company: 'CloudScale Dynamics',
      email: 'j.hayes@cloudscale.net',
      phone: '+1 (555) 567-8901',
      activeProjects: 0,
      totalValue: 9500000,
      status: 'Inactive',
      avatar: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000105'),
      name: 'NovaTech Solutions',
      company: 'NovaTech Solutions',
      email: 'm.chang@novatech.com',
      phone: '+1 (555) 678-9012',
      activeProjects: 1,
      totalValue: 11000000,
      status: 'Active',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000106'),
      name: 'Meridian Retail Group',
      company: 'Meridian Retail Group',
      email: 'sreynolds@meridianretail.com',
      phone: '+1 (555) 789-0123',
      activeProjects: 1,
      totalValue: 6500000,
      status: 'Active',
      avatar: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=150&auto=format&fit=crop&q=80',
    },
  ]);

  log(`[DevFlow Master Seed] Seeded ${clients.length} Clients`);

  // 3. Seed 12 Leads (NEW: 3, CONTACTED: 2, PROPOSAL: 2, NEGOTIATION: 2, CONVERTED: 2, LOST: 1)
  const leads = await Lead.create([
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000201'),
      name: 'Jonathan Vance',
      company: 'Nexus Global Logistics',
      email: 'j.vance@nexuslogistics.com',
      status: 'New',
      source: 'Partner Referral',
      value: 22000000,
      estimatedClose: '2026-12-01',
      assignedTo: 'Alex Morgan',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000202'),
      name: 'Marcus Thorne',
      company: 'Helios Energy Solutions',
      email: 'm.thorne@heliosenergy.com',
      status: 'New',
      source: 'Inbound Web Contact',
      value: 15000000,
      estimatedClose: '2026-11-20',
      assignedTo: 'Sarah Chen',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000203'),
      name: 'Laura Croft',
      company: 'Pinnacle Financial',
      email: 'l.croft@pinnaclefin.com',
      status: 'New',
      source: 'Tech Summit Conference',
      value: 18500000,
      estimatedClose: '2026-12-15',
      assignedTo: 'Rachel Wong',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000204'),
      name: 'Samantha Wright',
      company: 'Starlight Retail Technologies',
      email: 'swright@starlightretail.com',
      status: 'Contacted',
      source: 'LinkedIn Outreach',
      value: 9000000,
      estimatedClose: '2026-11-10',
      assignedTo: 'Sarah Chen',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000205'),
      name: 'Arthur Pendelton',
      company: 'Horizon Defense Labs',
      email: 'a.pendelton@horizonlabs.gov',
      status: 'Contacted',
      source: 'Enterprise RFP',
      value: 30000000,
      estimatedClose: '2026-11-30',
      assignedTo: 'Alex Morgan',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000206'),
      name: 'Jonathan Hayes',
      company: 'CloudScale Dynamics',
      email: 'j.hayes@cloudscale.net',
      status: 'Proposal',
      source: 'Inbound Web Contact',
      value: 9500000,
      estimatedClose: '2026-10-25',
      assignedTo: 'Sarah Chen',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000207'),
      name: 'Dr. Alistair Finch',
      company: 'Quantum BioSystems',
      email: 'a.finch@quantumbio.com',
      status: 'Proposal',
      source: 'Partner Referral',
      value: 14000000,
      estimatedClose: '2026-11-05',
      assignedTo: 'Rachel Wong',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000208'),
      name: 'Claire Redfield',
      company: 'Aegis Financial Solutions',
      email: 'c.redfield@aegisfin.io',
      status: 'Proposal',
      source: 'Enterprise RFP',
      value: 21000000,
      estimatedClose: '2026-10-30',
      assignedTo: 'Sarah Chen',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000209'),
      name: 'Sophia Reynolds',
      company: 'Meridian Retail Group',
      email: 'sreynolds@meridianretail.com',
      status: 'Proposal',
      source: 'Outbound Sales',
      value: 6500000,
      estimatedClose: '2026-10-15',
      assignedTo: 'Daniel Thomas',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000210'),
      name: 'Robert Sterling',
      company: 'Apex Capital Corp',
      email: 'robert.sterling@apexcapital.com',
      status: 'Converted',
      source: 'Enterprise RFP',
      value: 18000000,
      estimatedClose: '2026-01-10',
      assignedTo: 'Sarah Chen',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000211'),
      name: 'Dr. Aris Thorne',
      company: 'Vanguard Health Systems',
      email: 'athorne@vanguardhealth.org',
      status: 'Converted',
      source: 'Partner Referral',
      value: 12000000,
      estimatedClose: '2026-02-01',
      assignedTo: 'Rachel Wong',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000212'),
      name: 'Victor Vance',
      company: 'Metropolis Urban Planning',
      email: 'v.vance@metropolisplan.org',
      status: 'Lost',
      source: 'Outbound Cold Email',
      value: 5000000,
      estimatedClose: '2026-03-15',
      assignedTo: 'Olivia Bennett',
    },
  ]);

  log(`[DevFlow Master Seed] Seeded ${leads.length} Leads`);

  // 4. Seed 5 Projects
  const getUserRef = (idx: number) => ({
    id: users[idx]._id.toString(),
    name: users[idx].name,
    email: users[idx].email,
    role: users[idx].role as any,
    avatar: users[idx].avatar,
    workloadPercent: users[idx].workloadPercent,
  });

  const projects = await Project.create([
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000301'),
      name: 'Apex Enterprise Portal & Mobile App',
      clientName: 'Apex Capital Corp',
      description: 'Next-generation AI-driven financial portfolio analytics, real-time transaction processing, and secure mobile workspace.',
      manager: getUserRef(2), // Sarah Chen
      members: [getUserRef(5), getUserRef(7), getUserRef(8), getUserRef(10), getUserRef(11)], // Marcus, Elena, Arjun, David, Priya
      startDate: '2026-01-10',
      endDate: '2026-08-30',
      status: 'In Progress',
      priority: 'High',
      budget: 18000000,
      spent: 9500000,
      progress: 68,
      techStack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Redis', 'Tailwind CSS'],
      healthScore: 89,
      riskLevel: 'Low',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000302'),
      name: 'Vanguard Patient Care Platform',
      clientName: 'Vanguard Health Systems',
      description: 'HIPAA-compliant patient portal, telemedicine stream, and electronic health record AI triage system.',
      manager: getUserRef(3), // Rachel Wong
      members: [getUserRef(6), getUserRef(9), getUserRef(11)], // Nina, Kevin, Priya
      startDate: '2026-02-01',
      endDate: '2026-09-15',
      status: 'In Progress',
      priority: 'High',
      budget: 12000000,
      spent: 5000000,
      progress: 42,
      techStack: ['React', 'Python', 'PostgreSQL', 'Docker', 'AWS'],
      healthScore: 76,
      riskLevel: 'Moderate',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000303'),
      name: 'BioHealth Analytics Dashboard',
      clientName: 'BioHealth Innovations',
      description: 'Clinical trial analytics engine with real-time biometric visualization and predictive AI trial modeling.',
      manager: getUserRef(2), // Sarah Chen
      members: [getUserRef(7), getUserRef(10), getUserRef(11)], // Elena, David, Priya
      startDate: '2026-03-01',
      endDate: '2026-07-30',
      status: 'In Progress',
      priority: 'Medium',
      budget: 8500000,
      spent: 7400000,
      progress: 88,
      techStack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Python'],
      healthScore: 92,
      riskLevel: 'Low',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000304'),
      name: 'NovaTech Commerce Platform',
      clientName: 'NovaTech Solutions',
      description: 'Enterprise B2B e-commerce platform with automated multi-currency invoicing and inventory sync.',
      manager: getUserRef(3), // Rachel Wong
      members: [getUserRef(5), getUserRef(8), getUserRef(10)], // Marcus, Arjun, David
      startDate: '2026-01-05',
      endDate: '2026-05-20',
      status: 'Completed',
      priority: 'Medium',
      budget: 11000000,
      spent: 10500000,
      progress: 100,
      techStack: ['Next.js', 'Node.js', 'Redis', 'Tailwind CSS', 'Stripe'],
      healthScore: 96,
      riskLevel: 'Low',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000305'),
      name: 'Meridian Retail Intelligence',
      clientName: 'Meridian Retail Group',
      description: 'Omnichannel retail inventory AI forecaster with POS integration and automated reorder triggers.',
      manager: getUserRef(4), // Daniel Thomas
      members: [getUserRef(6), getUserRef(9)], // Nina, Kevin
      startDate: '2026-09-01',
      endDate: '2026-12-31',
      status: 'Planning',
      priority: 'Critical',
      budget: 6500000,
      spent: 800000,
      progress: 10,
      techStack: ['Python', 'React', 'PostgreSQL', 'Docker'],
      healthScore: 68,
      riskLevel: 'High',
    },
  ]);

  log(`[DevFlow Master Seed] Seeded ${projects.length} Projects`);

  // 5. Seed Milestones (18 total)
  const p1 = projects[0]._id.toString();
  const p2 = projects[1]._id.toString();
  const p3 = projects[2]._id.toString();
  const p4 = projects[3]._id.toString();
  const p5 = projects[4]._id.toString();

  const milestones = await Milestone.create([
    // Apex
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000401'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      title: 'Discovery & Requirements',
      description: 'Complete business requirement gathering, security audit, and system architecture blueprint.',
      status: 'Achieved',
      startDate: '2026-01-10',
      dueDate: '2026-02-28',
      progress: 100,
      relatedTasksCount: 4,
      owner: getUserRef(2),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000402'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      title: 'UX/UI Design',
      description: 'Figma design tokens, responsive web layouts, dark/light theme system, and client portal UI.',
      status: 'Achieved',
      startDate: '2026-03-01',
      dueDate: '2026-04-30',
      progress: 100,
      relatedTasksCount: 4,
      owner: getUserRef(10),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000403'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      title: 'Backend & API Development',
      description: 'OAuth2 pipeline, JWT refreshToken rotation, MongoDB schemas, and real-time transaction streaming.',
      status: 'In Progress',
      startDate: '2026-05-01',
      dueDate: '2026-06-30',
      progress: 75,
      relatedTasksCount: 4,
      owner: getUserRef(5),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000404'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      title: 'Frontend Implementation',
      description: 'Component architecture, state management, dashboard widget layout, and client portal view.',
      status: 'In Progress',
      startDate: '2026-06-01',
      dueDate: '2026-07-31',
      progress: 60,
      relatedTasksCount: 3,
      owner: getUserRef(8),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000405'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      title: 'QA & Production Launch',
      description: 'Automated E2E regression testing, load testing, security review, and final production release.',
      status: 'Upcoming',
      startDate: '2026-08-01',
      dueDate: '2026-08-30',
      progress: 20,
      relatedTasksCount: 3,
      owner: getUserRef(11),
    },

    // Vanguard
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000406'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      title: 'Healthcare Compliance & Architecture',
      description: 'HIPAA compliance audit, EHR data model design, and cloud security architecture.',
      status: 'Achieved',
      startDate: '2026-02-01',
      dueDate: '2026-03-15',
      progress: 100,
      relatedTasksCount: 3,
      owner: getUserRef(3),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000407'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      title: 'Patient Portal UI & Telemedicine Stream',
      description: 'Responsive patient dashboard, WebRTC video consultation, and prescription manager.',
      status: 'In Progress',
      startDate: '2026-03-16',
      dueDate: '2026-05-31',
      progress: 60,
      relatedTasksCount: 3,
      owner: getUserRef(6),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000408'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      title: 'EHR API Integration & Triage Engine',
      description: 'FastAPI EHR sync endpoints, Python AI medical symptom triage classifier.',
      status: 'In Progress',
      startDate: '2026-06-01',
      dueDate: '2026-07-31',
      progress: 30,
      relatedTasksCount: 3,
      owner: getUserRef(9),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000409'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      title: 'Clinical QA & Security Certification',
      description: 'End-to-end HIPAA compliance testing, penetration testing, and clinical deployment.',
      status: 'Upcoming',
      startDate: '2026-08-01',
      dueDate: '2026-09-15',
      progress: 0,
      relatedTasksCount: 3,
      owner: getUserRef(11),
    },

    // BioHealth
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000410'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      title: 'Data Pipeline & Ingestion Engine',
      description: 'Biometric stream ingestion pipeline, MongoDB time-series storage, and ETL data cleaning.',
      status: 'Achieved',
      startDate: '2026-03-01',
      dueDate: '2026-04-15',
      progress: 100,
      relatedTasksCount: 3,
      owner: getUserRef(7),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000411'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      title: 'Analytics Visualization Suite',
      description: 'Next.js interactive charts, real-time biometrics stream, and customizable dashboard widgets.',
      status: 'In Progress',
      startDate: '2026-04-16',
      dueDate: '2026-06-15',
      progress: 90,
      relatedTasksCount: 3,
      owner: getUserRef(10),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000412'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      title: 'Clinical Validation & Sign-off',
      description: 'Trial model verification with R&D team and final production deployment.',
      status: 'In Progress',
      startDate: '2026-06-16',
      dueDate: '2026-07-30',
      progress: 80,
      relatedTasksCount: 3,
      owner: getUserRef(11),
    },

    // NovaTech
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000413'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      title: 'Storefront Design & Architecture',
      description: 'Design system, catalog search layout, and microservice e-commerce blueprint.',
      status: 'Achieved',
      startDate: '2026-01-05',
      dueDate: '2026-02-15',
      progress: 100,
      relatedTasksCount: 3,
      owner: getUserRef(10),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000414'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      title: 'Payment Gateway & Inventory Sync',
      description: 'Stripe integration, multi-currency wallet, and real-time inventory locking API.',
      status: 'Achieved',
      startDate: '2026-02-16',
      dueDate: '2026-04-10',
      progress: 100,
      relatedTasksCount: 3,
      owner: getUserRef(5),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000415'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      title: 'Production Release & Handoff',
      description: 'Load testing under 1000 QPS, client documentation, and final production handoff.',
      status: 'Achieved',
      startDate: '2026-04-11',
      dueDate: '2026-05-20',
      progress: 100,
      relatedTasksCount: 3,
      owner: getUserRef(3),
    },

    // Meridian
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000416'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      title: 'Requirements Gathering & Scope Approval',
      description: 'Stakeholder interviews, POS API documentation review, and architecture planning.',
      status: 'In Progress',
      startDate: '2026-09-01',
      dueDate: '2026-09-30',
      progress: 30,
      relatedTasksCount: 3,
      owner: getUserRef(4),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000417'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      title: 'Retail POS Integration Pipeline',
      description: 'POS stream listener, transaction parser, and PostgreSQL store database.',
      status: 'Upcoming',
      startDate: '2026-10-01',
      dueDate: '2026-11-15',
      progress: 0,
      relatedTasksCount: 2,
      owner: getUserRef(6),
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000418'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      title: 'ML Demand Forecasting Engine',
      description: 'Python machine learning model for retail demand forecasting and automated reordering.',
      status: 'Upcoming',
      startDate: '2026-11-16',
      dueDate: '2026-12-31',
      progress: 0,
      relatedTasksCount: 2,
      owner: getUserRef(9),
    },
  ]);

  log(`[DevFlow Master Seed] Seeded ${milestones.length} Milestones`);

  // 6. Seed 55 Tasks with Subtasks
  const m1 = milestones[0]._id.toString();
  const m2 = milestones[1]._id.toString();
  const m3 = milestones[2]._id.toString();
  const m4 = milestones[3]._id.toString();
  const m5 = milestones[4]._id.toString();
  const m6 = milestones[5]._id.toString();
  const m7 = milestones[6]._id.toString();
  const m8 = milestones[7]._id.toString();
  const m9 = milestones[8]._id.toString();
  const m10 = milestones[9]._id.toString();
  const m11 = milestones[10]._id.toString();
  const m12 = milestones[11]._id.toString();
  const m13 = milestones[12]._id.toString();
  const m14 = milestones[13]._id.toString();
  const m15 = milestones[14]._id.toString();
  const m16 = milestones[15]._id.toString();
  const m17 = milestones[16]._id.toString();
  const m18 = milestones[17]._id.toString();

  const tasksData = [
    // Apex Tasks (18)
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000501'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m1,
      title: 'Finalize Product Requirements Specification',
      description: 'Draft comprehensive system architecture specification and obtain client sign-off.',
      assignee: getUserRef(2),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-01-25',
      tags: ['Planning', 'Requirement'],
      subtasks: [
        { id: 'st-101', title: 'Gather functional requirements', completed: true },
        { id: 'st-102', title: 'Sign off with Apex Capital CTO', completed: true },
      ],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000502'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m1,
      title: 'Approve System Architecture Blueprint',
      description: 'Define component diagrams, microservice boundaries, and database schema models.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-02-20',
      tags: ['Architecture', 'Security'],
      subtasks: [
        { id: 'st-103', title: 'Draft ERD and MongoDB schema models', completed: true },
        { id: 'st-104', title: 'Conduct internal architecture peer review', completed: true },
      ],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000503'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m1,
      title: 'Security & Compliance Assessment',
      description: 'Perform threat modeling, data classification, and SOC2 compliance audit.',
      assignee: getUserRef(0),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-02-25',
      tags: ['Security', 'Compliance'],
      subtasks: [{ id: 'st-105', title: 'Document SOC2 controls map', completed: true }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000504'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m1,
      title: 'Setup Infrastructure & CI/CD Pipeline',
      description: 'Provision AWS ECS cluster, GitHub Actions workflow, and Docker registry.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'Critical',
      dueDate: '2026-02-28',
      tags: ['DevOps', 'AWS'],
      subtasks: [{ id: 'st-106', title: 'Configure GitHub Actions CI runner', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000505'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m2,
      title: 'Design Enterprise Dark/Light Theme System',
      description: 'Refine UI components, CSS design tokens, typography, and contrast accessibility.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-03-20',
      tags: ['Design', 'UI/UX', 'Tailwind CSS'],
      subtasks: [
        { id: 'st-107', title: 'Create Figma design token library', completed: true },
        { id: 'st-108', title: 'Implement Tailwind globals.css custom theme', completed: true },
      ],
      commentsCount: 5,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000506'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m2,
      title: 'Build Responsive Dashboard Layout & Navigation',
      description: 'Implement executive dashboard layout, interactive KPI summary cards, and sidebar.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-04-10',
      tags: ['Frontend', 'React', 'Dashboard'],
      subtasks: [{ id: 'st-109', title: 'Build responsive sidebar navigation pill', completed: true }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000507'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m2,
      title: 'Implement Client Portal UI & File Manager',
      description: 'Build authenticated client dashboard overview, project milestones timeline, and documents.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-04-28',
      tags: ['Frontend', 'Client Portal', 'UI'],
      subtasks: [{ id: 'st-110', title: 'Implement file download action handlers', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000508'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m2,
      title: 'Design Mobile Responsive Layouts & Touch Controls',
      description: 'Optimize mobile web viewports, swipe gestures, and drawer navigation menus.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-04-30',
      tags: ['Design', 'Mobile', 'UI'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000509'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m3,
      title: 'Implement JWT Authentication & Session Rotation',
      description: 'Set up HttpOnly session cookies, refreshToken rotation, and authenticator TOTP verification.',
      assignee: getUserRef(5),
      status: 'In Progress',
      priority: 'Critical',
      dueDate: '2026-05-25',
      tags: ['Security', 'Backend', 'Auth'],
      subtasks: [
        { id: 'st-111', title: 'Setup JWT helper utilities', completed: true },
        { id: 'st-112', title: 'Implement refresh token rotation model', completed: true },
        { id: 'st-113', title: 'Integrate TOTP QR code generator', completed: false },
      ],
      commentsCount: 6,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000510'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m3,
      title: 'Build Project & Milestone API Services',
      description: 'Create Mongoose CRUD endpoints for projects, tasks, milestones, and automated progress sync.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-05-30',
      tags: ['Backend', 'MongoDB', 'API'],
      subtasks: [{ id: 'st-114', title: 'Build project CRUD controller handlers', completed: true }],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000511'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m3,
      title: 'Build Client & Lead Management APIs',
      description: 'Implement CRM backend controllers for managing lead stages, client records, and meetings.',
      assignee: getUserRef(7),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-06-05',
      tags: ['CRM', 'Backend', 'API'],
      subtasks: [{ id: 'st-115', title: 'Create lead model schemas & pipeline filters', completed: true }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000512'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m3,
      title: 'Redis Caching & Real-Time Socket Stream API',
      description: 'Build Redis pub/sub socket connection to stream real-time financial ledger updates.',
      assignee: getUserRef(7),
      status: 'In Progress',
      priority: 'Critical',
      dueDate: '2026-06-28',
      tags: ['Backend', 'Redis', 'WebSockets'],
      subtasks: [
        { id: 'st-116', title: 'Build Redis pub/sub channel handler', completed: true },
        { id: 'st-117', title: 'Integrate client socket listener', completed: false },
      ],
      commentsCount: 5,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000513'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m4,
      title: 'Build Interactive Financial Chart Components',
      description: 'Develop Recharts portfolio growth, budget vs actuals, and cashflow projection widgets.',
      assignee: getUserRef(8),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-06-20',
      tags: ['Frontend', 'Recharts', 'Analytics'],
      subtasks: [{ id: 'st-118', title: 'Integrate portfolio growth line chart', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000514'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m4,
      title: 'Implement Notification Center UI & Preferences',
      description: 'Build real-time notification toast, unread badge counter, and filter settings.',
      assignee: getUserRef(8),
      status: 'In Progress',
      priority: 'Medium',
      dueDate: '2026-07-15',
      tags: ['Frontend', 'Notifications'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000515'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m4,
      title: 'Integrate Global Workspace Search Bar',
      description: 'Build unified instant search modal across projects, tasks, clients, and documents.',
      assignee: getUserRef(8),
      status: 'Review',
      priority: 'Medium',
      dueDate: '2026-07-28',
      tags: ['Frontend', 'Search'],
      subtasks: [{ id: 'st-119', title: 'Build keyboard shortcut listener (Cmd+K)', completed: true }],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000516'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m5,
      title: 'API Integration Test Suite',
      description: 'Build comprehensive Postman and Jest test collections verifying response contracts.',
      assignee: getUserRef(11),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-08-10',
      tags: ['QA', 'Testing', 'Jest'],
      subtasks: [{ id: 'st-120', title: 'Jest API route integration specs', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000517'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m5,
      title: 'Authentication & Security Access Test Suite',
      description: 'Verify password hashing security, session token revocation, and role permissions.',
      assignee: getUserRef(11),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-08-20',
      tags: ['QA', 'Security', 'Testing'],
      subtasks: [{ id: 'st-121', title: 'Check RBAC role route permission blocks', completed: false }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000518'),
      projectId: p1,
      projectName: 'Apex Enterprise Portal & Mobile App',
      milestoneId: m5,
      title: 'Production Docker & Deployment Runbook',
      description: 'Prepare production Docker Compose configuration, SSL certificates, and deployment scripts.',
      assignee: getUserRef(0),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-08-28',
      tags: ['DevOps', 'Docker', 'Deployment'],
      subtasks: [{ id: 'st-122', title: 'Configure Docker compose production file', completed: true }],
      commentsCount: 2,
    },

    // Vanguard Tasks (12)
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000519'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m6,
      title: 'HIPAA Compliance Security Audit',
      description: 'Review PHI encryption at rest and in transit according to HIPAA guidelines.',
      assignee: getUserRef(6),
      status: 'Completed',
      priority: 'Critical',
      dueDate: '2026-02-20',
      tags: ['HIPAA', 'Security'],
      subtasks: [{ id: 'st-201', title: 'Audit AWS KMS encryption keys', completed: true }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000520'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m6,
      title: 'EHR Data Schema Architecture Design',
      description: 'Design FHIR-compliant PostgreSQL database schema for medical history.',
      assignee: getUserRef(6),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-03-05',
      tags: ['Database', 'PostgreSQL'],
      subtasks: [],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000521'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m6,
      title: 'Patient Portal Wireframe Prototyping',
      description: 'Create accessible high-fidelity wireframes for senior patient consultation portal.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-03-15',
      tags: ['Design', 'UI/UX'],
      subtasks: [{ id: 'st-202', title: 'Figma accessibility review', completed: true }],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000522'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m7,
      title: 'Build Patient Appointment Booking Interface',
      description: 'Develop interactive doctor calendar slot selector with automated SMS alerts.',
      assignee: getUserRef(9),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-04-10',
      tags: ['Frontend', 'React'],
      subtasks: [{ id: 'st-203', title: 'Integrate Twilio SMS API', completed: true }],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000523'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m7,
      title: 'Integrate WebRTC Telemedicine Video Stream',
      description: 'Set up peer-to-peer encrypted WebRTC video consultation room.',
      assignee: getUserRef(6),
      status: 'In Progress',
      priority: 'Critical',
      dueDate: '2026-05-15',
      tags: ['WebRTC', 'Video'],
      subtasks: [{ id: 'st-204', title: 'STUN/TURN server deployment', completed: true }],
      commentsCount: 5,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000524'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m7,
      title: 'Build E-Prescription Management UI',
      description: 'Create doctor prescription generator with pharmacy API integration.',
      assignee: getUserRef(9),
      status: 'In Progress',
      priority: 'Medium',
      dueDate: '2026-05-30',
      tags: ['Frontend', 'Pharmacy'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000525'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m8,
      title: 'FastAPI EHR Data Sync Engine',
      description: 'Build high-throughput Python API service for synchronizing patient records.',
      assignee: getUserRef(6),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-06-20',
      tags: ['Python', 'FastAPI'],
      subtasks: [{ id: 'st-205', title: 'Write FHIR parser endpoints', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000526'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m8,
      title: 'AI Medical Symptom Triage Classifier',
      description: 'Train NLP medical symptom classifier for emergency patient triage.',
      assignee: getUserRef(6),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-07-10',
      tags: ['AI', 'Python', 'NLP'],
      subtasks: [],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000527'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m8,
      title: 'Audit Logging & Encryption Key Manager',
      description: 'Implement immutable access logs for all medical record queries.',
      assignee: getUserRef(9),
      status: 'Todo',
      priority: 'High',
      dueDate: '2026-07-25',
      tags: ['Security', 'Audit'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000528'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m9,
      title: 'HIPAA Automated Security Penetration Test',
      description: 'Execute OWASP ZAP and automated penetration testing scripts against staging.',
      assignee: getUserRef(11),
      status: 'Todo',
      priority: 'Critical',
      dueDate: '2026-08-15',
      tags: ['QA', 'Security'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000529'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m9,
      title: 'Clinical User Acceptance Testing (UAT)',
      description: 'Conduct UAT with Vanguard medical staff and hospital administrators.',
      assignee: getUserRef(3),
      status: 'Todo',
      priority: 'High',
      dueDate: '2026-08-30',
      tags: ['UAT', 'Clinical'],
      subtasks: [],
      commentsCount: 0,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000530'),
      projectId: p2,
      projectName: 'Vanguard Patient Care Platform',
      milestoneId: m9,
      title: 'Production AWS Cloud Deployment',
      description: 'Deploy multi-region AWS EKS cluster with automated failover.',
      assignee: getUserRef(6),
      status: 'Todo',
      priority: 'High',
      dueDate: '2026-09-10',
      tags: ['DevOps', 'AWS'],
      subtasks: [],
      commentsCount: 0,
    },

    // BioHealth Tasks (10)
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000531'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m10,
      title: 'Biometric Stream Ingestion Service',
      description: 'Build real-time wearable device telemetry ingestion endpoint.',
      assignee: getUserRef(7),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-03-25',
      tags: ['IoT', 'Node.js'],
      subtasks: [{ id: 'st-301', title: 'Write telemetry payload schema validator', completed: true }],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000532'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m10,
      title: 'MongoDB Time-Series Data Collection',
      description: 'Configure optimized MongoDB time-series collections for trial patient metrics.',
      assignee: getUserRef(7),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-04-05',
      tags: ['MongoDB', 'Time-Series'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000533'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m10,
      title: 'Data Cleaning & Outlier Removal Pipeline',
      description: 'Implement Python pandas data cleaning script for noisy biometric data.',
      assignee: getUserRef(7),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-04-12',
      tags: ['Python', 'Pandas'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000534'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m11,
      title: 'Interactive Clinical Metric Charts',
      description: 'Build Next.js real-time heartbeat and blood oxygen level line charts.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-05-10',
      tags: ['Frontend', 'Recharts'],
      subtasks: [{ id: 'st-302', title: 'Integrate SVG streaming canvas', completed: true }],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000535'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m11,
      title: 'Trial Cohort Comparison Matrix Widget',
      description: 'Develop multi-patient trial cohort metrics comparison table.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-05-25',
      tags: ['Frontend', 'React'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000536'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m11,
      title: 'Predictive Trial Efficacy Model API',
      description: 'Deploy scikit-learn model predicting 90-day clinical trial success rates.',
      assignee: getUserRef(7),
      status: 'Review',
      priority: 'High',
      dueDate: '2026-06-10',
      tags: ['AI', 'Python'],
      subtasks: [],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000537'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m12,
      title: 'Clinical Data Export PDF/Excel Engine',
      description: 'Build automated PDF report generator for medical board presentation.',
      assignee: getUserRef(10),
      status: 'In Progress',
      priority: 'Medium',
      dueDate: '2026-06-25',
      tags: ['Reporting', 'PDF'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000538'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m12,
      title: 'Automated QA Validation Suite',
      description: 'Write Jest unit tests verifying telemetry calculation accuracy.',
      assignee: getUserRef(11),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-07-10',
      tags: ['QA', 'Jest'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000539'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m12,
      title: 'BioHealth R&D Team Sign-off Meeting',
      description: 'Conduct final demonstration with BioHealth Chief Scientific Officer.',
      assignee: getUserRef(2),
      status: 'Todo',
      priority: 'High',
      dueDate: '2026-07-25',
      tags: ['Client', 'Demo'],
      subtasks: [],
      commentsCount: 0,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000540'),
      projectId: p3,
      projectName: 'BioHealth Analytics Dashboard',
      milestoneId: m12,
      title: 'Production Production Release Verification',
      description: 'Verify production database backup and load balancing stability.',
      assignee: getUserRef(7),
      status: 'Todo',
      priority: 'Medium',
      dueDate: '2026-07-28',
      tags: ['DevOps', 'Deployment'],
      subtasks: [],
      commentsCount: 0,
    },

    // NovaTech Tasks (9)
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000541'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m13,
      title: 'B2B Catalog Layout Wireframes',
      description: 'Design responsive catalog product grid with multi-tier price tables.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-01-20',
      tags: ['Design', 'UI'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000542'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m13,
      title: 'Product Catalog Microservice API',
      description: 'Build Node.js catalog query endpoint with MongoDB indexing.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-02-05',
      tags: ['Backend', 'MongoDB'],
      subtasks: [],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000543'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m13,
      title: 'Figma E-Commerce UI Token Spec',
      description: 'Create brand design tokens for NovaTech storefront component library.',
      assignee: getUserRef(10),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-02-14',
      tags: ['Design', 'Figma'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000544'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m14,
      title: 'Stripe Payments Checkout Integration',
      description: 'Implement Stripe Checkout API with automated webhook confirmation.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'Critical',
      dueDate: '2026-03-10',
      tags: ['Stripe', 'Payment'],
      subtasks: [{ id: 'st-401', title: 'Configure Stripe webhook listener', completed: true }],
      commentsCount: 4,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000545'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m14,
      title: 'Redis Inventory Lock Manager',
      description: 'Implement atomic Redis inventory reservation during shopping cart checkout.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-03-25',
      tags: ['Redis', 'Inventory'],
      subtasks: [],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000546'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m14,
      title: 'Automated Multi-Currency Invoicing API',
      description: 'Build currency exchange sync endpoint for B2B global clients.',
      assignee: getUserRef(8),
      status: 'Completed',
      priority: 'Medium',
      dueDate: '2026-04-05',
      tags: ['API', 'Finance'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000547'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m15,
      title: 'Load Testing Under 1000 QPS Load',
      description: 'Execute k6 load test scripts simulating peak holiday shopping traffic.',
      assignee: getUserRef(8),
      status: 'Completed',
      priority: 'Critical',
      dueDate: '2026-04-25',
      tags: ['Testing', 'LoadTest'],
      subtasks: [],
      commentsCount: 3,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000548'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m15,
      title: 'NovaTech VP Sign-off & Handoff',
      description: 'Final presentation and operational runbook handoff to NovaTech team.',
      assignee: getUserRef(3),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-05-10',
      tags: ['Handoff', 'Client'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000549'),
      projectId: p4,
      projectName: 'NovaTech Commerce Platform',
      milestoneId: m15,
      title: 'Production Cutover & Domain Switch',
      description: 'Update DNS CNAME record to point domain to production server.',
      assignee: getUserRef(5),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-05-20',
      tags: ['DevOps', 'DNS'],
      subtasks: [],
      commentsCount: 1,
    },

    // Meridian Tasks (6)
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000550'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m16,
      title: 'Stakeholder Interviews & Feature Discovery',
      description: 'Conduct interviews with Meridian retail store managers to identify pain points.',
      assignee: getUserRef(4),
      status: 'Completed',
      priority: 'High',
      dueDate: '2026-09-10',
      tags: ['Discovery', 'Retail'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000551'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m16,
      title: 'Meridian POS API Documentation Audit',
      description: 'Review legacy POS endpoint schemas and authentication requirements.',
      assignee: getUserRef(6),
      status: 'In Progress',
      priority: 'Medium',
      dueDate: '2026-09-20',
      tags: ['POS', 'API'],
      subtasks: [],
      commentsCount: 1,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000552'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m16,
      title: 'Draft Project Architecture Specification',
      description: 'Outline system architecture, data pipeline, and predictive model scope.',
      assignee: getUserRef(4),
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-09-30',
      tags: ['Architecture', 'Planning'],
      subtasks: [],
      commentsCount: 2,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000553'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m17,
      title: 'Build POS Stream Listener Microservice',
      description: 'Develop Python socket listener consuming real-time store sales events.',
      assignee: getUserRef(6),
      status: 'Todo',
      priority: 'High',
      dueDate: '2026-10-20',
      tags: ['Python', 'Sockets'],
      subtasks: [],
      commentsCount: 0,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000554'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m17,
      title: 'PostgreSQL Store Transactions Schema',
      description: 'Design relational database tables for store inventory levels.',
      assignee: getUserRef(9),
      status: 'Todo',
      priority: 'Medium',
      dueDate: '2026-11-05',
      tags: ['PostgreSQL', 'Schema'],
      subtasks: [],
      commentsCount: 0,
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000555'),
      projectId: p5,
      projectName: 'Meridian Retail Intelligence',
      milestoneId: m18,
      title: 'Train Demand Forecasting AI Model',
      description: 'Build Python machine learning model forecasting 30-day product demand.',
      assignee: getUserRef(9),
      status: 'Todo',
      priority: 'Critical',
      dueDate: '2026-12-10',
      tags: ['AI', 'Python', 'ML'],
      subtasks: [],
      commentsCount: 0,
    },
  ];

  const tasks = [];
  for (const t of tasksData) {
    const created = await Task.create(t);
    tasks.push(created);
  }

  log(`[DevFlow Master Seed] Seeded ${tasks.length} Tasks`);

  // 7. Seed 16 Meetings
  const meetings = await Meeting.create([
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000601'),
      title: 'Apex Capital Project Kickoff & Requirements Review',
      clientName: 'Apex Capital Corp',
      date: '2026-01-15',
      time: '10:00 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Alex Morgan', 'Sarah Chen', 'Marcus Vance', 'Robert Sterling'],
      notes: 'Confirmed project scope, budget (₹1,80,00,000), milestone timeline, and core security requirements.',
      outcome: 'Approved master scope and authorized sprint planning.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000602'),
      title: 'Architecture & OAuth2 Security Review',
      clientName: 'Apex Capital Corp',
      date: '2026-02-12',
      time: '14:00 EST',
      duration: '45 mins',
      status: 'Completed',
      participants: ['Marcus Vance', 'Elena Rostova', 'Robert Sterling'],
      notes: 'Reviewed JWT refresh token rotation, HttpOnly cookie security, and multi-factor auth pipeline.',
      outcome: 'Architecture approved for production beta deployment.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000603'),
      title: 'UI/UX Design System Review',
      clientName: 'Apex Capital Corp',
      date: '2026-04-10',
      time: '15:00 EST',
      duration: '45 mins',
      status: 'Completed',
      participants: ['David Kim', 'Sarah Chen', 'Robert Sterling'],
      notes: 'Presented Figma design system, dark/light theme switching, and responsive client portal layouts.',
      outcome: 'UI design system approved for frontend integration.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000604'),
      title: 'Sprint 4 Review & Client Alignment Meeting',
      clientName: 'Apex Capital Corp',
      date: '2026-10-10',
      time: '11:00 EST',
      duration: '45 mins',
      status: 'Scheduled',
      participants: ['Alex Morgan', 'Sarah Chen', 'David Kim', 'Robert Sterling'],
      notes: 'Demonstrate responsive UI dark/light theme, client dashboard analytics, and preview real-time transaction streaming.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000605'),
      title: 'QA Readiness & Pre-Deployment Review',
      clientName: 'Apex Capital Corp',
      date: '2026-10-25',
      time: '14:00 EST',
      duration: '60 mins',
      status: 'Scheduled',
      participants: ['Priya Patel', 'Marcus Vance', 'Robert Sterling'],
      notes: 'Review automated E2E test results, load testing benchmarks, and final production release checklist.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000606'),
      title: 'Vanguard Health Telemedicine Architecture Alignment',
      clientName: 'Vanguard Health Systems',
      date: '2026-02-10',
      time: '11:00 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Rachel Wong', 'Nina Thomas', 'Dr. Aris Thorne'],
      notes: 'Finalized HIPAA encryption protocols and WebRTC video consultation room specifications.',
      outcome: 'Approved HIPAA compliance architecture.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000607'),
      title: 'Vanguard Patient Care Sprint 3 Review',
      clientName: 'Vanguard Health Systems',
      date: '2026-05-15',
      time: '10:00 EST',
      duration: '45 mins',
      status: 'Completed',
      participants: ['Rachel Wong', 'Kevin Joseph', 'Dr. Aris Thorne'],
      notes: 'Demonstrated appointment booking interface and patient medical history dashboard.',
      outcome: 'Client approved sprint 3 deliverables.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000608'),
      title: 'Vanguard EHR API Integration Sync',
      clientName: 'Vanguard Health Systems',
      date: '2026-10-18',
      time: '13:00 EST',
      duration: '45 mins',
      status: 'Scheduled',
      participants: ['Nina Thomas', 'Kevin Joseph', 'Dr. Aris Thorne'],
      notes: 'Review Python FastAPI FHIR data parser endpoints and patient record sync performance.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000609'),
      title: 'BioHealth Biometric Pipeline Review',
      clientName: 'BioHealth Innovations',
      date: '2026-03-28',
      time: '16:00 EST',
      duration: '50 mins',
      status: 'Completed',
      participants: ['Sarah Chen', 'Elena Rostova', 'Dr. Evelyn Vance'],
      notes: 'Reviewed IoT wearable data ingestion throughput and MongoDB time-series storage.',
      outcome: 'Data pipeline passed ingestion benchmark.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000610'),
      title: 'BioHealth Analytics Dashboard Demo',
      clientName: 'BioHealth Innovations',
      date: '2026-06-02',
      time: '14:00 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Sarah Chen', 'David Kim', 'Dr. Evelyn Vance'],
      notes: 'Demonstrated real-time SVG streaming charts and clinical trial cohort comparison widget.',
      outcome: 'BioHealth team requested final PDF export module.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000611'),
      title: 'BioHealth Predictive Model Validation Meeting',
      clientName: 'BioHealth Innovations',
      date: '2026-10-22',
      time: '15:00 EST',
      duration: '45 mins',
      status: 'Scheduled',
      participants: ['Elena Rostova', 'Priya Patel', 'Dr. Evelyn Vance'],
      notes: 'Review scikit-learn 90-day trial success forecasting model accuracy.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000612'),
      title: 'NovaTech B2B Commerce Kickoff Meeting',
      clientName: 'NovaTech Solutions',
      date: '2026-01-08',
      time: '09:30 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Rachel Wong', 'Marcus Vance', 'Michael Chang'],
      notes: 'Established multi-currency catalog requirements and Stripe payments integration scope.',
      outcome: 'Approved initial contract and sprint milestones.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000613'),
      title: 'NovaTech Storefront Release & Production Handoff',
      clientName: 'NovaTech Solutions',
      date: '2026-05-18',
      time: '11:00 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Rachel Wong', 'Marcus Vance', 'Michael Chang'],
      notes: 'Delivered production runbook, API documentation, and DNS cutover verification.',
      outcome: 'Project successfully completed and accepted by NovaTech.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000614'),
      title: 'Meridian Retail Group Discovery Session',
      clientName: 'Meridian Retail Group',
      date: '2026-09-08',
      time: '14:00 EST',
      duration: '60 mins',
      status: 'Completed',
      participants: ['Daniel Thomas', 'Nina Thomas', 'Sophia Reynolds'],
      notes: 'Interviewed retail operations leads regarding POS transaction data format.',
      outcome: 'Defined preliminary system architecture.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000615'),
      title: 'Meridian Retail POS Architecture Alignment',
      clientName: 'Meridian Retail Group',
      date: '2026-10-14',
      time: '10:00 EST',
      duration: '45 mins',
      status: 'Scheduled',
      participants: ['Daniel Thomas', 'Nina Thomas', 'Sophia Reynolds'],
      notes: 'Review proposed Python socket stream listener architecture and store database schema.',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000616'),
      title: 'CloudScale Dynamics Proposal Review',
      clientName: 'CloudScale Dynamics',
      date: '2026-10-12',
      time: '16:00 EST',
      duration: '45 mins',
      status: 'Scheduled',
      participants: ['Sarah Chen', 'Alex Morgan', 'Jonathan Hayes'],
      notes: 'Present enterprise cloud optimization proposal and contract scope.',
    },
  ]);

  log(`[DevFlow Master Seed] Seeded ${meetings.length} Meetings`);

  // 8. Seed 16 Documents
  const documentsData = [
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000701'),
      name: 'Apex_Enterprise_Portal_Requirements_Specification_v1.0.pdf',
      category: 'Requirement',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '3.4 MB',
      sizeBytes: 3565158,
      uploadedBy: 'Sarah Chen',
      uploadDate: '2026-01-18',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000702'),
      name: 'Apex_Portal_System_Architecture_Blueprint.pdf',
      category: 'Architecture',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '4.8 MB',
      sizeBytes: 5033164,
      uploadedBy: 'Marcus Vance',
      uploadDate: '2026-02-10',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000703'),
      name: 'Master_Services_Agreement_ApexCapital.pdf',
      category: 'Contract',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '1.2 MB',
      sizeBytes: 1258291,
      uploadedBy: 'Alex Morgan',
      uploadDate: '2026-01-12',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000704'),
      name: 'Apex_Portal_UI_UX_Design_System_Specification.pdf',
      category: 'Design',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '5.1 MB',
      sizeBytes: 5347737,
      uploadedBy: 'David Kim',
      uploadDate: '2026-03-18',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000705'),
      name: 'E2E_Test_Plan_and_QA_Automated_Suite.docx',
      category: 'Requirement',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '2.1 MB',
      sizeBytes: 2202009,
      uploadedBy: 'Priya Patel',
      uploadDate: '2026-06-02',
      fileType: 'DOCX',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000706'),
      name: 'Apex_Portal_Production_Deployment_Runbook.pdf',
      category: 'Architecture',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '1.8 MB',
      sizeBytes: 1887436,
      uploadedBy: 'Alex Morgan',
      uploadDate: '2026-06-20',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000707'),
      name: 'Vanguard_HIPAA_Compliance_Security_Assessment.pdf',
      category: 'Requirement',
      projectName: 'Vanguard Patient Care Platform',
      projectId: p2,
      size: '3.9 MB',
      sizeBytes: 4089446,
      uploadedBy: 'Rachel Wong',
      uploadDate: '2026-02-22',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000708'),
      name: 'Vanguard_EHR_Integration_Architecture.pdf',
      category: 'Architecture',
      projectName: 'Vanguard Patient Care Platform',
      projectId: p2,
      size: '2.7 MB',
      sizeBytes: 2831155,
      uploadedBy: 'Nina Thomas',
      uploadDate: '2026-03-08',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000709'),
      name: 'Vanguard_Telemedicine_WebRTC_Specification.pdf',
      category: 'Architecture',
      projectName: 'Vanguard Patient Care Platform',
      projectId: p2,
      size: '1.9 MB',
      sizeBytes: 1992294,
      uploadedBy: 'Kevin Joseph',
      uploadDate: '2026-04-12',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000710'),
      name: 'BioHealth_Biometric_Data_Pipeline_Blueprint.pdf',
      category: 'Architecture',
      projectName: 'BioHealth Analytics Dashboard',
      projectId: p3,
      size: '3.1 MB',
      sizeBytes: 3250585,
      uploadedBy: 'Elena Rostova',
      uploadDate: '2026-03-15',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000711'),
      name: 'BioHealth_Clinical_Trial_Efficacy_Model_Doc.docx',
      category: 'Requirement',
      projectName: 'BioHealth Analytics Dashboard',
      projectId: p3,
      size: '2.4 MB',
      sizeBytes: 2516582,
      uploadedBy: 'Sarah Chen',
      uploadDate: '2026-05-18',
      fileType: 'DOCX',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000712'),
      name: 'NovaTech_Commerce_Stripe_Integration_Guide.pdf',
      category: 'Architecture',
      projectName: 'NovaTech Commerce Platform',
      projectId: p4,
      size: '1.5 MB',
      sizeBytes: 1572864,
      uploadedBy: 'Marcus Vance',
      uploadDate: '2026-03-02',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000713'),
      name: 'NovaTech_Load_Test_Benchmark_Results.pdf',
      category: 'Requirement',
      projectName: 'NovaTech Commerce Platform',
      projectId: p4,
      size: '2.8 MB',
      sizeBytes: 2936012,
      uploadedBy: 'Arjun Nair',
      uploadDate: '2026-04-28',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000714'),
      name: 'Meridian_Retail_POS_Discovery_Report.pdf',
      category: 'Requirement',
      projectName: 'Meridian Retail Intelligence',
      projectId: p5,
      size: '2.0 MB',
      sizeBytes: 2097152,
      uploadedBy: 'Daniel Thomas',
      uploadDate: '2026-09-12',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000715'),
      name: 'Meridian_Demand_Forecasting_AI_Proposal.pdf',
      category: 'Contract',
      projectName: 'Meridian Retail Intelligence',
      projectId: p5,
      size: '3.3 MB',
      sizeBytes: 3460300,
      uploadedBy: 'Olivia Bennett',
      uploadDate: '2026-09-25',
      fileType: 'PDF',
      url: '',
    },
    {
      _id: new mongoose.Types.ObjectId('650000000000000000000716'),
      name: 'DevFlow_Master_Enterprise_Security_Policy.pdf',
      category: 'Requirement',
      projectName: 'Apex Enterprise Portal & Mobile App',
      projectId: p1,
      size: '4.2 MB',
      sizeBytes: 4404019,
      uploadedBy: 'Alex Morgan',
      uploadDate: '2026-01-05',
      fileType: 'PDF',
      url: '',
    },
  ];

  const documents = await DocumentModel.create(documentsData);

  for (const doc of documents) {
    doc.url = `/api/documents/${doc._id}/download`;
    await doc.save();
  }

  log(`[DevFlow Master Seed] Seeded ${documents.length} Documents`);

  // 9. Seed 30 Notifications
  const notificationSeeds = [];
  const notifTypes: ('task' | 'milestone' | 'meeting' | 'ai')[] = ['task', 'milestone', 'meeting', 'ai'];

  for (let i = 1; i <= 30; i++) {
    const hex = i.toString(16).padStart(2, '0');
    const assignedUser = users[(i - 1) % users.length];
    const targetType = notifTypes[(i - 1) % notifTypes.length];
    
    let title = '';
    let message = '';

    if (targetType === 'task') {
      title = 'Task Assignment Updated';
      message = `${assignedUser.name} was assigned task #${i} in flagship project.`;
    } else if (targetType === 'milestone') {
      title = 'Milestone Progress Update';
      message = `Milestone #${(i % 5) + 1} reached target progress checkpoint.`;
    } else if (targetType === 'meeting') {
      title = 'Client Meeting Reminder';
      message = `Upcoming client review scheduled for ${assignedUser.name}.`;
    } else {
      title = 'AI Project Intelligence Alert';
      message = `AI Project Assistant generated risk analysis report for active sprint.`;
    }

    notificationSeeds.push({
      _id: new mongoose.Types.ObjectId(`6500000000000000000008${hex}`),
      userId: assignedUser._id.toString(),
      type: targetType,
      title,
      message,
      timestamp: `${i * 2} hours ago`,
      read: i % 3 === 0,
      priority: i % 4 === 0 ? 'high' : 'medium',
      entityId: tasks[i % tasks.length]._id.toString(),
      entityType: targetType,
      projectId: p1,
      actionUrl: `/tasks?projectId=${p1}`,
    });
  }

  const notifications = await NotificationModel.create(notificationSeeds);
  log(`[DevFlow Master Seed] Seeded ${notifications.length} Notifications`);

  // 10. Seed 75 Activity Logs
  const activitySeeds = [];
  const actionsList = [
    'Lead Created',
    'Lead Contacted',
    'Proposal Submitted',
    'Lead Converted',
    'Client Created',
    'Project Created',
    'Milestone Created',
    'Task Status Updated',
    'Task Completed',
    'Meeting Scheduled',
    'Document Uploaded',
    'Project Progress Updated',
    'Project Health Updated',
    'User Assigned to Project',
    'Security Audit Completed',
  ];

  for (let i = 1; i <= 75; i++) {
    const hex = i.toString(16).padStart(2, '0');
    const user = users[(i - 1) % users.length];
    const action = actionsList[(i - 1) % actionsList.length];
    const prj = projects[(i - 1) % projects.length];

    activitySeeds.push({
      _id: new mongoose.Types.ObjectId(`6500000000000000000009${hex}`),
      userName: user.name,
      userRole: user.role,
      userAvatar: user.avatar,
      action,
      entity: `Activity #${i}: ${action} for ${prj.name}`,
      projectName: prj.name,
      projectId: prj._id.toString(),
      timestamp: `${i} hours ago`,
      description: `${user.name} (${user.role}) executed ${action.toLowerCase()} on ${prj.name}.`,
    });
  }

  const activityLogs = await ActivityLogModel.create(activitySeeds);
  log(`[DevFlow Master Seed] Seeded ${activityLogs.length} Activity Logs`);

  log('[DevFlow Master Seed] SUCCESS: Master database seeding completed with 100% clean presentation dataset!');
};

if (require.main === module) {
  seedMasterDatabase()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[DevFlow Master Seed Error]', err);
      process.exit(1);
    });
}
