import {
  Project,
  Task,
  Milestone,
  TeamMember,
  Lead,
  Client,
  Meeting,
  DocumentItem,
  NotificationItem,
  ActivityLogItem,
  User,
} from '@/types';

export const currentUser: User = {
  id: 'usr-001',
  name: 'Alex Morgan',
  email: 'alex.morgan@devflow.io',
  role: 'Super Admin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  department: 'Engineering Leadership',
};

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Sarah Chen',
    email: 'sarah.c@devflow.io',
    role: 'Project Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    skills: ['Agile', 'Scrum', 'Jira', 'Stakeholder Management', 'Risk Analysis'],
    assignedProjects: ['FinTech Nexus Suite', 'HealthPulse Mobile Platform'],
    workloadPercent: 78,
    availability: 'Available',
    performanceRating: 4.9,
    joinedDate: '2023-01-15',
  },
  {
    id: 'tm-2',
    name: 'Marcus Vance',
    email: 'marcus.v@devflow.io',
    role: 'Team Lead',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    skills: ['React', 'Next.js', 'Node.js', 'TypeScript', 'GraphQL', 'System Architecture'],
    assignedProjects: ['FinTech Nexus Suite', 'LogiTrack Supply Chain'],
    workloadPercent: 92,
    availability: 'Busy',
    performanceRating: 4.8,
    joinedDate: '2022-08-01',
  },
  {
    id: 'tm-3',
    name: 'Elena Rostova',
    email: 'elena.r@devflow.io',
    role: 'Developer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    skills: ['Python', 'FastAPI', 'PyTorch', 'MongoDB', 'Redis', 'Docker'],
    assignedProjects: ['AI Knowledge Engine'],
    workloadPercent: 65,
    availability: 'Available',
    performanceRating: 4.7,
    joinedDate: '2023-05-10',
  },
  {
    id: 'tm-4',
    name: 'David Kim',
    email: 'david.k@devflow.io',
    role: 'Designer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'Prototyping', 'User Research'],
    assignedProjects: ['FinTech Nexus Suite', 'HealthPulse Mobile Platform'],
    workloadPercent: 45,
    availability: 'Available',
    performanceRating: 4.9,
    joinedDate: '2023-03-20',
  },
  {
    id: 'tm-5',
    name: 'Priya Patel',
    email: 'priya.p@devflow.io',
    role: 'QA',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    skills: ['Cypress', 'Jest', 'Automation', 'Load Testing', 'Postman'],
    assignedProjects: ['LogiTrack Supply Chain', 'HealthPulse Mobile Platform'],
    workloadPercent: 80,
    availability: 'Available',
    performanceRating: 4.6,
    joinedDate: '2023-09-01',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'prj-101',
    name: 'FinTech Nexus Suite',
    clientName: 'Apex Capital Corp',
    description: 'Next-generation AI-driven financial portfolio analytics and real-time transaction processing platform.',
    manager: currentUser,
    members: mockTeamMembers.slice(0, 3),
    startDate: '2026-01-10',
    endDate: '2026-08-30',
    status: 'In Progress',
    priority: 'High',
    budget: 180000,
    spent: 95000,
    progress: 68,
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Redis', 'Tailwind'],
    healthScore: 92,
    riskLevel: 'Low',
  },
  {
    id: 'prj-102',
    name: 'AI Knowledge Engine',
    clientName: 'Vanguard Systems',
    description: 'Enterprise RAG knowledge base synthesizer with semantic search & automated documentation generation.',
    manager: currentUser,
    members: [mockTeamMembers[2], mockTeamMembers[1]],
    startDate: '2026-02-01',
    endDate: '2026-06-15',
    status: 'In Progress',
    priority: 'Critical',
    budget: 120000,
    spent: 45000,
    progress: 42,
    techStack: ['Python', 'FastAPI', 'LangChain', 'Pinecone', 'React', 'Tailwind'],
    healthScore: 78,
    riskLevel: 'Moderate',
  },
  {
    id: 'prj-103',
    name: 'HealthPulse Mobile Platform',
    clientName: 'BioHealth Innovations',
    description: 'HIPAA-compliant telemedicine dashboard and patient monitoring mobile app ecosystem.',
    manager: currentUser,
    members: [mockTeamMembers[0], mockTeamMembers[3], mockTeamMembers[4]],
    startDate: '2025-11-01',
    endDate: '2026-04-30',
    status: 'Review',
    priority: 'Medium',
    budget: 95000,
    spent: 89000,
    progress: 88,
    techStack: ['React Native', 'Node.js', 'Express', 'MongoDB', 'AWS S3'],
    healthScore: 85,
    riskLevel: 'Low',
  },
  {
    id: 'prj-104',
    name: 'LogiTrack Supply Chain',
    clientName: 'Global Freight Networks',
    description: 'IoT shipment tracker with predictive delay alerts and automated invoice reconciliation.',
    manager: currentUser,
    members: [mockTeamMembers[1], mockTeamMembers[4]],
    startDate: '2026-03-01',
    endDate: '2026-11-20',
    status: 'Planning',
    priority: 'High',
    budget: 210000,
    spent: 20000,
    progress: 15,
    techStack: ['Go', 'Vue.js', 'PostgreSQL', 'Docker', 'Kubernetes'],
    healthScore: 95,
    riskLevel: 'Low',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk-201',
    projectId: 'prj-101',
    projectName: 'FinTech Nexus Suite',
    title: 'Implement OAuth2 & Multi-Factor Auth JWT Pipeline',
    description: 'Set up HttpOnly session cookies, refreshToken rotation, and authenticator app TOTP verification.',
    assignee: mockTeamMembers[1],
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-09-30',
    tags: ['Security', 'Backend', 'Auth'],
    subtasks: [
      { id: 'st-1', title: 'Setup JWT helper utilities', completed: true },
      { id: 'st-2', title: 'Implement refresh token rotation model', completed: true },
      { id: 'st-3', title: 'Integrate TOTP QR code generator', completed: false },
    ],
    commentsCount: 5,
    createdAt: '2026-09-20',
  },
  {
    id: 'tsk-202',
    projectId: 'prj-101',
    projectName: 'FinTech Nexus Suite',
    title: 'Design Dashboard Dark Mode Glassmorphism System',
    description: 'Refine shadcn/ui components, CSS design tokens, typography, and contrast accessibility.',
    assignee: mockTeamMembers[3],
    status: 'Review',
    priority: 'Medium',
    dueDate: '2026-09-28',
    tags: ['Design', 'UI/UX', 'Tailwind'],
    subtasks: [
      { id: 'st-4', title: 'Create Figma design token library', completed: true },
      { id: 'st-5', title: 'Implement Tailwind globals.css custom theme', completed: true },
    ],
    commentsCount: 3,
    createdAt: '2026-09-18',
  },
  {
    id: 'tsk-203',
    projectId: 'prj-102',
    projectName: 'AI Knowledge Engine',
    title: 'Benchmark Vector Database Query Latency',
    description: 'Optimize Pinecone index hybrid search queries and measure response time under 100 QPS load.',
    assignee: mockTeamMembers[2],
    status: 'Todo',
    priority: 'Critical',
    dueDate: '2026-10-05',
    tags: ['AI', 'Performance', 'Python'],
    subtasks: [
      { id: 'st-6', title: 'Write load test script using Locust', completed: false },
      { id: 'st-7', title: 'Tune vector embedding dimensionality', completed: false },
    ],
    commentsCount: 2,
    createdAt: '2026-09-22',
  },
  {
    id: 'tsk-204',
    projectId: 'prj-103',
    projectName: 'HealthPulse Mobile Platform',
    title: 'E2E Automated Regression Suite for Video Calls',
    description: 'Build WebRTC connection testing scripts using Cypress and test WebSockets signaling server.',
    assignee: mockTeamMembers[4],
    status: 'Completed',
    priority: 'High',
    dueDate: '2026-09-24',
    tags: ['QA', 'Testing', 'Cypress'],
    subtasks: [
      { id: 'st-8', title: 'Configure Cypress WebRTC mocks', completed: true },
      { id: 'st-9', title: 'Verify audio stream reconnection flow', completed: true },
    ],
    commentsCount: 7,
    createdAt: '2026-09-10',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'ms-301',
    projectId: 'prj-101',
    projectName: 'FinTech Nexus Suite',
    title: 'Core Portfolio Engine & Real-time Analytics Beta',
    description: 'Deploy real-time stock websocket stream and basic transaction ledger to staging environment.',
    status: 'In Progress',
    startDate: '2026-08-01',
    dueDate: '2026-10-15',
    progress: 75,
    relatedTasksCount: 14,
    owner: mockTeamMembers[1],
  },
  {
    id: 'ms-302',
    projectId: 'prj-102',
    projectName: 'AI Knowledge Engine',
    title: 'RAG Pipeline & Custom Document Ingestion API',
    description: 'Support PDF, DOCX, and Markdown parsing with automatic chunking and embedding storage.',
    status: 'Upcoming',
    startDate: '2026-09-15',
    dueDate: '2026-11-01',
    progress: 35,
    relatedTasksCount: 9,
    owner: mockTeamMembers[2],
  },
  {
    id: 'ms-303',
    projectId: 'prj-103',
    projectName: 'HealthPulse Mobile Platform',
    title: 'HIPAA Audit Compliance & Security Review',
    description: 'Complete third-party penetration testing and end-to-end data encryption verification.',
    status: 'Achieved',
    startDate: '2026-07-10',
    dueDate: '2026-09-20',
    progress: 100,
    relatedTasksCount: 12,
    owner: mockTeamMembers[0],
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'ld-401',
    name: 'Robert Sterling',
    company: 'Sterling Global Logistics',
    email: 'r.sterling@sterlinglogistics.com',
    status: 'Proposal',
    source: 'Inbound Web Contact',
    value: 145000,
    estimatedClose: '2026-10-20',
    assignedTo: 'Sarah Chen',
  },
  {
    id: 'ld-402',
    name: 'Samantha Wright',
    company: 'Quantum Health Tech',
    email: 'swright@quantumhealth.io',
    status: 'Contacted',
    source: 'LinkedIn Outreach',
    value: 90000,
    estimatedClose: '2026-11-10',
    assignedTo: 'Sarah Chen',
  },
  {
    id: 'ld-403',
    name: 'Jonathan Vance',
    company: 'NextGen Financials',
    email: 'j.vance@nextgenfin.com',
    status: 'New',
    source: 'Partner Referral',
    value: 220000,
    estimatedClose: '2026-12-01',
    assignedTo: 'Alex Morgan',
  },
];

export const mockClients: Client[] = [
  {
    id: 'cli-501',
    name: 'Apex Capital Corp',
    company: 'Apex Capital Corp',
    email: 'contact@apexcapital.com',
    phone: '+1 (555) 234-5678',
    activeProjects: 1,
    totalValue: 180000,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'cli-502',
    name: 'Vanguard Systems',
    company: 'Vanguard Systems',
    email: 'info@vanguardsys.com',
    phone: '+1 (555) 876-5432',
    activeProjects: 1,
    totalValue: 120000,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'cli-503',
    name: 'BioHealth Innovations',
    company: 'BioHealth Innovations',
    email: 'partners@biohealth.org',
    phone: '+1 (555) 345-6789',
    activeProjects: 1,
    totalValue: 95000,
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'mtg-601',
    title: 'FinTech Nexus Architecture & Security Sprint Review',
    clientName: 'Apex Capital Corp',
    date: '2026-09-28',
    time: '14:00 EST',
    duration: '45 mins',
    status: 'Scheduled',
    participants: ['Alex Morgan', 'Sarah Chen', 'Marcus Vance', 'Apex CTO'],
    notes: 'Review OAuth2 implementation progress, load testing metrics, and Q4 delivery timeline.',
  },
  {
    id: 'mtg-602',
    title: 'AI Knowledge Engine Milestone Sign-off',
    clientName: 'Vanguard Systems',
    date: '2026-09-30',
    time: '11:00 EST',
    duration: '30 mins',
    status: 'Scheduled',
    participants: ['Alex Morgan', 'Elena Rostova', 'Vanguard Product Director'],
    notes: 'Demonstrate semantic document extraction accuracy and review Pinecone API latency report.',
  },
];

export const mockDocuments: DocumentItem[] = [
  {
    id: 'doc-701',
    name: 'FinTech_Nexus_System_Architecture_v2.4.pdf',
    category: 'Architecture',
    size: '4.8 MB',
    uploadedBy: 'Marcus Vance',
    uploadDate: '2026-09-15',
    projectName: 'FinTech Nexus Suite',
    fileType: 'PDF',
  },
  {
    id: 'doc-702',
    name: 'Master_Services_Agreement_ApexCapital.pdf',
    category: 'Contract',
    size: '1.2 MB',
    uploadedBy: 'Sarah Chen',
    uploadDate: '2026-01-08',
    projectName: 'FinTech Nexus Suite',
    fileType: 'PDF',
  },
  {
    id: 'doc-703',
    name: 'AI_Knowledge_Engine_RAG_Requirements_Specification.docx',
    category: 'Requirement',
    size: '2.5 MB',
    uploadedBy: 'Elena Rostova',
    uploadDate: '2026-02-05',
    projectName: 'AI Knowledge Engine',
    fileType: 'DOCX',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'ntf-801',
    type: 'ai',
    title: 'AI Risk Alert: Resource Overload Warning',
    message: 'Marcus Vance workload reached 92%. AI suggests delegating task tsk-201 subtasks to Elena Rostova.',
    timestamp: '10 mins ago',
    read: false,
    priority: 'high',
  },
  {
    id: 'ntf-802',
    type: 'milestone',
    title: 'Milestone Achieved!',
    message: 'HealthPulse HIPAA Audit Compliance milestone achieved ahead of schedule.',
    timestamp: '2 hours ago',
    read: false,
    priority: 'medium',
  },
  {
    id: 'ntf-803',
    type: 'task',
    title: 'Task Review Requested',
    message: 'David Kim moved "Design Dashboard Dark Mode Glassmorphism System" to Review.',
    timestamp: '1 day ago',
    read: true,
    priority: 'low',
  },
];

export const mockActivityLogs: ActivityLogItem[] = [
  {
    id: 'act-901',
    userName: 'Marcus Vance',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action: 'Updated Status',
    entity: 'Task: Implement OAuth2 & Multi-Factor Auth JWT Pipeline',
    timestamp: '15 minutes ago',
    description: 'Moved task status from Todo to In Progress and completed 2 subtasks.',
  },
  {
    id: 'act-902',
    userName: 'Sarah Chen',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action: 'Created Milestone',
    entity: 'Milestone: RAG Pipeline & Custom Document Ingestion API',
    timestamp: '2 hours ago',
    description: 'Set target due date to November 1st, 2026 with 9 associated tasks.',
  },
  {
    id: 'act-903',
    userName: 'Alex Morgan',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'Uploaded Document',
    entity: 'Document: FinTech_Nexus_System_Architecture_v2.4.pdf',
    timestamp: '1 day ago',
    description: 'Uploaded revised backend system architecture documentation.',
  },
];
